### ISSUE TITLE
Scraper does not run 

### ISSUE THREAD

**Issue by Krynh** [DelgadoJosh/WanderingInnScraper#14]
It has previously downloaded 20 pages but then got stuck re-downloading the same one. Now it doesn't do anything at all.

Currently Scraping https://wanderinginn.com/2023/06/05/9-42-e/ - 9.42 E
Word Count: 11349, Chapter Word Count: 11349
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "wanderingInnScraperBackEnd.py", line 166, in scrapePageInit
  File "wanderingInnScraperBackEnd.py", line 203, in scrapePage
IndexError: list index out of range

**Comment by DelgadoJosh** [comment]
Thanks for reporting this! It's looking like the wandering inn site now has a guard against scraping pages, seems to limit you to like 10-20 pages before it stops you from scraping more, at least with this project

I'm currently looking into seeing what I can do to mitigate this in the mean time.  Unfortunately it seems the only short term workaround is to download a few chapters at a time.

**Comment by Krynh** [comment]
Yeah I got ip banned for scraping those 22, I just tried 5 just now and that didn't work either.

**Comment by DelgadoJosh** [comment]
So I think it goes away after some period of time, based on some reports I've read, hopefully it'll work for you in the future!

**Comment by DelgadoJosh** [comment]
In the meantime I'm going to put a big warning on the readme to not use this until I find a better workaround

**Comment by Krynh** [comment]
It worked to download the edited volume 1 chapters and let me download 3 more of 9

**Comment by VellichorDetroit** [comment]
I'm having the same issue! Would rotating proxies or implementing a waiting period between each request be helpful?

**Comment by Krynh** [comment]
The issue fixes itself if you change your IP address as the site has banned your IP due to the many requests
